-- vim.g.mapleader = ' '
-- local map = vim.api.nvim_set_keymap

-- map('n', '<C-S>', ':w<cr>', {noremap = true, silent = false})
-- map('i', '<C-S>', '<C-o>:w<cr>', {noremap = true, silent = false})
-- map('n', '<C-q>', ':q<cr>', {noremap = true, silent = false})
-- map('i', '<C-q>', '<C-o>:q<cr>', {noremap = true, silent = false})
-- map('n', '<C-x>', ':x<cr>', {noremap = true, silent = false})
-- map('i', '<C-x>', '<C-o>:x<cr>', {noremap = true, silent = false})
-- map('i', '<C-BS>', '<C-W>', {noremap = true, silent = false})

-- map('n', '<C-p>', ':Telescope find_files<cr>', {noremap = true, silent = false})
-- map('n', '<C-f>', ':Telescope live_grep<cr>', {noremap = true, silent = false})

-- local opts = { noremap=true, silent=true }
-- map('n', 'gD', '<cmd>lua vim.lsp.buf.declaration()<CR>', opts)
-- map('n', 'gd', '<cmd>lua vim.lsp.buf.definition()<CR>', opts)
-- map('n', 'K', '<cmd>lua vim.lsp.buf.hover()<CR>', opts)
-- map('n', 'gi', '<cmd>lua vim.lsp.buf.implementation()<CR>', opts)
-- map('n', '<C-k>', '<cmd>lua vim.lsp.buf.signature_help()<CR>', opts)
-- map('n', '<space>wa', '<cmd>lua vim.lsp.buf.add_workspace_folder()<CR>', opts)
-- map('n', '<space>wr', '<cmd>lua vim.lsp.buf.remove_workspace_folder()<CR>', opts)
-- map('n', '<space>wl', '<cmd>lua print(vim.inspect(vim.lsp.buf.list_workspace_folders()))<CR>', opts)
-- map('n', '<space>D', '<cmd>lua vim.lsp.buf.type_definition()<CR>', opts)
-- map('n', '<space>rn', '<cmd>lua vim.lsp.buf.rename()<CR>', opts)
-- map('n', '<space>ca', '<cmd>lua vim.lsp.buf.code_action()<CR>', opts)
-- map('n', 'gr', '<cmd>lua vim.lsp.buf.references()<CR>', opts)
-- map('n', '<space>e', '<cmd>lua vim.diagnostic.open_float()<CR>', opts)
-- map('n', '[d', '<cmd>lua vim.diagnostic.goto_prev()<CR>', opts)
-- map('n', ']d', '<cmd>lua vim.diagnostic.goto_next()<CR>', opts)
-- map('n', '<space>q', '<cmd>lua vim.diagnostic.setloclist()<CR>', opts)
-- map('n', '<space>f', '<cmd>lua vim.lsp.buf.formatting()<CR>', opts)
